/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Juego.Juego;
import java.awt.Color;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 *
 * @author Joel
 */
public class Seleccion extends javax.swing.JFrame {

    private String posInicial;
    
    /**
     * Creates new form Seleccion
     */
    public Seleccion() {
        initComponents();
        getContentPane().setBackground(Color.white);
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(jButton1);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreCipayos = new javax.swing.JTextField();
        nombreMaharaja = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton27 = new javax.swing.JToggleButton();
        jToggleButton28 = new javax.swing.JToggleButton();
        jToggleButton29 = new javax.swing.JToggleButton();
        jToggleButton30 = new javax.swing.JToggleButton();
        jToggleButton31 = new javax.swing.JToggleButton();
        jToggleButton32 = new javax.swing.JToggleButton();
        jToggleButton33 = new javax.swing.JToggleButton();
        jToggleButton34 = new javax.swing.JToggleButton();
        jToggleButton35 = new javax.swing.JToggleButton();
        jToggleButton37 = new javax.swing.JToggleButton();
        jToggleButton38 = new javax.swing.JToggleButton();
        jToggleButton39 = new javax.swing.JToggleButton();
        jToggleButton40 = new javax.swing.JToggleButton();
        jToggleButton41 = new javax.swing.JToggleButton();
        jToggleButton42 = new javax.swing.JToggleButton();
        jToggleButton43 = new javax.swing.JToggleButton();
        jToggleButton44 = new javax.swing.JToggleButton();
        jToggleButton45 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Define la batalla");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Titania", 0, 36)); // NOI18N
        jLabel1.setText("Cipayos, ¿Cuál es tu nombre?");

        jLabel2.setFont(new java.awt.Font("Titania", 0, 36)); // NOI18N
        jLabel2.setText("¿Quién será el Maharajá?");

        nombreCipayos.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        nombreCipayos.setText("Derrota al rebelde...");
        nombreCipayos.setNextFocusableComponent(jToggleButton8);
        nombreCipayos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreCipayosMouseClicked(evt);
            }
        });
        nombreCipayos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCipayosActionPerformed(evt);
            }
        });
        nombreCipayos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreCipayosFocusGained(evt);
            }
        });
        nombreCipayos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreCipayosKeyReleased(evt);
            }
        });

        nombreMaharaja.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        nombreMaharaja.setText("Acaba con todo un ejército...");
        nombreMaharaja.setNextFocusableComponent(nombreCipayos);
        nombreMaharaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreMaharajaMouseClicked(evt);
            }
        });
        nombreMaharaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreMaharajaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Titania", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("¡Que comience la batalla!");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(4, 9));

        jToggleButton7.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton7.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton7.setText("3");
        jToggleButton7.setBorderPainted(false);
        jToggleButton7.setEnabled(false);
        jPanel1.add(jToggleButton7);

        jToggleButton8.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jToggleButton8);
        jToggleButton8.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton8.setNextFocusableComponent(jButton1);
        jToggleButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton8);

        jToggleButton9.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jToggleButton9);
        jToggleButton9.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton9.setNextFocusableComponent(jButton1);
        jToggleButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton9);

        jToggleButton10.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jToggleButton10);
        jToggleButton10.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton10.setNextFocusableComponent(jButton1);
        jToggleButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton10);

        jToggleButton11.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jToggleButton11);
        jToggleButton11.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton11.setNextFocusableComponent(jButton1);
        jToggleButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton11);

        jToggleButton12.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jToggleButton12);
        jToggleButton12.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton12.setNextFocusableComponent(jButton1);
        jToggleButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton12);

        jToggleButton13.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jToggleButton13);
        jToggleButton13.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton13.setNextFocusableComponent(jButton1);
        jToggleButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton13);

        jToggleButton14.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jToggleButton14);
        jToggleButton14.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton14.setNextFocusableComponent(jButton1);
        jToggleButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton14);

        jToggleButton15.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jToggleButton15);
        jToggleButton15.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton15.setNextFocusableComponent(jButton1);
        jToggleButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton15);

        jToggleButton17.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton17.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton17.setText("2");
        jToggleButton17.setBorderPainted(false);
        jToggleButton17.setEnabled(false);
        jPanel1.add(jToggleButton17);

        jToggleButton18.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jToggleButton18);
        jToggleButton18.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton18.setNextFocusableComponent(jButton1);
        jToggleButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton18);

        jToggleButton19.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jToggleButton19);
        jToggleButton19.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton19.setNextFocusableComponent(jButton1);
        jToggleButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton19);

        jToggleButton20.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jToggleButton20);
        jToggleButton20.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton20.setNextFocusableComponent(jButton1);
        jToggleButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton20);

        jToggleButton21.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jToggleButton21);
        jToggleButton21.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton21.setNextFocusableComponent(jButton1);
        jToggleButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton21);

        jToggleButton22.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jToggleButton22);
        jToggleButton22.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton22.setNextFocusableComponent(jButton1);
        jToggleButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton22);

        jToggleButton23.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jToggleButton23);
        jToggleButton23.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton23.setNextFocusableComponent(jButton1);
        jToggleButton23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton23);

        jToggleButton24.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jToggleButton24);
        jToggleButton24.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton24.setNextFocusableComponent(jButton1);
        jToggleButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton24ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton24);

        jToggleButton25.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jToggleButton25);
        jToggleButton25.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton25.setNextFocusableComponent(jButton1);
        jToggleButton25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton25ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton25);

        jToggleButton27.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton27.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton27.setText("1");
        jToggleButton27.setBorderPainted(false);
        jToggleButton27.setEnabled(false);
        jPanel1.add(jToggleButton27);

        jToggleButton28.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jToggleButton28);
        jToggleButton28.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton28.setNextFocusableComponent(jButton1);
        jToggleButton28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton28ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton28);

        jToggleButton29.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jToggleButton29);
        jToggleButton29.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton29.setNextFocusableComponent(jButton1);
        jToggleButton29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton29ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton29);

        jToggleButton30.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jToggleButton30);
        jToggleButton30.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton30.setNextFocusableComponent(jButton1);
        jToggleButton30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton30ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton30);

        jToggleButton31.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jToggleButton31);
        jToggleButton31.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton31.setNextFocusableComponent(jButton1);
        jToggleButton31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton31ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton31);

        jToggleButton32.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jToggleButton32);
        jToggleButton32.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton32.setNextFocusableComponent(jButton1);
        jToggleButton32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton32ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton32);

        jToggleButton33.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jToggleButton33);
        jToggleButton33.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton33.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton33.setNextFocusableComponent(jButton1);
        jToggleButton33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton33ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton33);

        jToggleButton34.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(jToggleButton34);
        jToggleButton34.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton34.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton34.setNextFocusableComponent(jButton1);
        jToggleButton34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton34ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton34);

        jToggleButton35.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jToggleButton35);
        jToggleButton35.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton35.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton35.setNextFocusableComponent(jButton1);
        jToggleButton35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton35ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton35);

        jToggleButton37.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton37.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton37.setBorderPainted(false);
        jToggleButton37.setEnabled(false);
        jPanel1.add(jToggleButton37);

        jToggleButton38.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton38.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton38.setText("a");
        jToggleButton38.setBorderPainted(false);
        jToggleButton38.setEnabled(false);
        jPanel1.add(jToggleButton38);

        jToggleButton39.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton39.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton39.setText("b");
        jToggleButton39.setBorderPainted(false);
        jToggleButton39.setEnabled(false);
        jPanel1.add(jToggleButton39);

        jToggleButton40.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton40.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton40.setText("c");
        jToggleButton40.setBorderPainted(false);
        jToggleButton40.setEnabled(false);
        jPanel1.add(jToggleButton40);

        jToggleButton41.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton41.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton41.setText("d");
        jToggleButton41.setBorderPainted(false);
        jToggleButton41.setEnabled(false);
        jPanel1.add(jToggleButton41);

        jToggleButton42.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton42.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton42.setText("e");
        jToggleButton42.setBorderPainted(false);
        jToggleButton42.setEnabled(false);
        jPanel1.add(jToggleButton42);

        jToggleButton43.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton43.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton43.setText("f");
        jToggleButton43.setBorderPainted(false);
        jToggleButton43.setEnabled(false);
        jPanel1.add(jToggleButton43);

        jToggleButton44.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton44.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton44.setText("g");
        jToggleButton44.setBorderPainted(false);
        jToggleButton44.setEnabled(false);
        jPanel1.add(jToggleButton44);

        jToggleButton45.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton45.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jToggleButton45.setText("h");
        jToggleButton45.setBorderPainted(false);
        jToggleButton45.setEnabled(false);
        jPanel1.add(jToggleButton45);

        jLabel3.setFont(new java.awt.Font("Titania", 0, 36)); // NOI18N
        jLabel3.setText("¿Dónde comenzará el Maharajá?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreMaharaja, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombreCipayos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 69, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreMaharaja, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nombreCipayos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreMaharajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreMaharajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreMaharajaActionPerformed

    private void nombreMaharajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreMaharajaMouseClicked
        // TODO add your handling code here:
        nombreMaharaja.setText("");
    }//GEN-LAST:event_nombreMaharajaMouseClicked

    private void nombreCipayosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreCipayosMouseClicked
        // TODO add your handling code here:
        nombreCipayos.setText("");
    }//GEN-LAST:event_nombreCipayosMouseClicked

    private void nombreCipayosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCipayosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCipayosActionPerformed

    private void nombreCipayosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreCipayosKeyReleased
        // TODO add your handling code here
        enableNext();
    }//GEN-LAST:event_nombreCipayosKeyReleased

    public void enableNext() {
        String entryM = nombreMaharaja.getText().replaceAll("\\s+","");
        String entryC = nombreCipayos.getText().replaceAll("\\s+","");
        
        if (!entryC.isEmpty() && !entryM.isEmpty() && 
            !"Acabacontodounejército...".equals(entryM) && 
            !"Derrotaalrebelde...".equals(entryC) &&
            !entryC.equals(entryM) && buttonGroup1.getSelection() != null) {
            jButton1.setEnabled(true); 
        } 
        else { jButton1.setEnabled(false); }
    }
    
    private void nombreCipayosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreCipayosFocusGained
        // TODO add your handling code here:
        nombreCipayos.setText("");
    }//GEN-LAST:event_nombreCipayosFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();

        String jugCipayos  = nombreCipayos.getText();
        String jugMaharaja = nombreMaharaja.getText();
        
        int x = Integer.parseInt(posInicial.split(",")[0]);
        int y = Integer.parseInt(posInicial.split(",")[1]);
        
        ExecutorService executor = Executors.newCachedThreadPool();
        
        try {
            executor.execute(new Juego(false, false, jugCipayos, jugMaharaja, x, y));
        } 
        catch (Exception e) { }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        // TODO add your handling code here:
        setPosInicial("5,0"); enableNext();
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        // TODO add your handling code here:
        setPosInicial("5,1"); enableNext();
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        // TODO add your handling code here:
        setPosInicial("5,2"); enableNext();
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        // TODO add your handling code here:
        setPosInicial("5,3"); enableNext();
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
        // TODO add your handling code here:
        setPosInicial("5,4"); enableNext();
    }//GEN-LAST:event_jToggleButton12ActionPerformed

    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
        // TODO add your handling code here:
        setPosInicial("5,5"); enableNext();
    }//GEN-LAST:event_jToggleButton13ActionPerformed

    private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton14ActionPerformed
        // TODO add your handling code here:
        setPosInicial("5,6"); enableNext();
    }//GEN-LAST:event_jToggleButton14ActionPerformed

    private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton15ActionPerformed
        // TODO add your handling code here:
        setPosInicial("5,7"); enableNext();
    }//GEN-LAST:event_jToggleButton15ActionPerformed

    private void jToggleButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton18ActionPerformed
        // TODO add your handling code here:
        setPosInicial("6,0"); enableNext();
    }//GEN-LAST:event_jToggleButton18ActionPerformed

    private void jToggleButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton19ActionPerformed
        // TODO add your handling code here:
        setPosInicial("6,1"); enableNext();
    }//GEN-LAST:event_jToggleButton19ActionPerformed

    private void jToggleButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton20ActionPerformed
        // TODO add your handling code here:
        setPosInicial("6,2"); enableNext();
    }//GEN-LAST:event_jToggleButton20ActionPerformed

    private void jToggleButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton21ActionPerformed
        // TODO add your handling code here:
        setPosInicial("6,3"); enableNext();
    }//GEN-LAST:event_jToggleButton21ActionPerformed

    private void jToggleButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton22ActionPerformed
        // TODO add your handling code here:
        setPosInicial("6,4"); enableNext();
    }//GEN-LAST:event_jToggleButton22ActionPerformed

    private void jToggleButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton23ActionPerformed
        // TODO add your handling code here:
        setPosInicial("6,5"); enableNext();
    }//GEN-LAST:event_jToggleButton23ActionPerformed

    private void jToggleButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton24ActionPerformed
        // TODO add your handling code here:
        setPosInicial("6,6"); enableNext();
    }//GEN-LAST:event_jToggleButton24ActionPerformed

    private void jToggleButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton25ActionPerformed
        // TODO add your handling code here:
        setPosInicial("6,7"); enableNext();
    }//GEN-LAST:event_jToggleButton25ActionPerformed

    private void jToggleButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton28ActionPerformed
        // TODO add your handling code here:
        setPosInicial("7,0"); enableNext();
    }//GEN-LAST:event_jToggleButton28ActionPerformed

    private void jToggleButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton29ActionPerformed
        // TODO add your handling code here:
        setPosInicial("7,1"); enableNext();
    }//GEN-LAST:event_jToggleButton29ActionPerformed

    private void jToggleButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton30ActionPerformed
        // TODO add your handling code here:
        setPosInicial("7,2"); enableNext();
    }//GEN-LAST:event_jToggleButton30ActionPerformed

    private void jToggleButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton31ActionPerformed
        // TODO add your handling code here:
        setPosInicial("7,3"); enableNext();
    }//GEN-LAST:event_jToggleButton31ActionPerformed

    private void jToggleButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton32ActionPerformed
        // TODO add your handling code here:
        setPosInicial("7,4"); enableNext();
    }//GEN-LAST:event_jToggleButton32ActionPerformed

    private void jToggleButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton33ActionPerformed
        // TODO add your handling code here:
        setPosInicial("7,5"); enableNext();
    }//GEN-LAST:event_jToggleButton33ActionPerformed

    private void jToggleButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton34ActionPerformed
        // TODO add your handling code here:
        setPosInicial("7,6"); enableNext();
    }//GEN-LAST:event_jToggleButton34ActionPerformed

    private void jToggleButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton35ActionPerformed
        // TODO add your handling code here:
        setPosInicial("7,7"); enableNext();
    }//GEN-LAST:event_jToggleButton35ActionPerformed

    private void jToggleButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton8MouseClicked

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

   
    public void setPosInicial(String pos) {
        this.posInicial = pos;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton31;
    private javax.swing.JToggleButton jToggleButton32;
    private javax.swing.JToggleButton jToggleButton33;
    private javax.swing.JToggleButton jToggleButton34;
    private javax.swing.JToggleButton jToggleButton35;
    private javax.swing.JToggleButton jToggleButton37;
    private javax.swing.JToggleButton jToggleButton38;
    private javax.swing.JToggleButton jToggleButton39;
    private javax.swing.JToggleButton jToggleButton40;
    private javax.swing.JToggleButton jToggleButton41;
    private javax.swing.JToggleButton jToggleButton42;
    private javax.swing.JToggleButton jToggleButton43;
    private javax.swing.JToggleButton jToggleButton44;
    private javax.swing.JToggleButton jToggleButton45;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JTextField nombreCipayos;
    private javax.swing.JTextField nombreMaharaja;
    // End of variables declaration//GEN-END:variables
}
